path:
  work_dir: "D:/GitHubD/BREDS"
  test_pairs: "test_pairs.txt"
  unseen_objects: "data_numeric/unseen_objects.txt"
  seeds_file: "data_numeric/seeds_positive.txt"
  negative_seeds: "data_numeric/seeds_negative.txt"
  objects: "data_numeric/VG_YOLO_intersection_train.txt"
  vg_objects: "D:/GitHubD/visual-size-comparison/data/objects.json"
  vg_objects_anchors: "D:/GitHubD/visual-size-comparison/data/test_objects.csv"
  final_seeds_cache: "notable_runs/visual_no_coref/final_seeds_20200525-180627.json"
  patterns:
    coref:
      visual: "notable_runs/20200521visualandcoref/patterns_20200521-134836.pkl"
      no_visual: "notable_runs/20200520novisualwithcoref/patterns_20200520-232753.pkl"
    no_coref:
      visual: "todo.pkl"
      no_visual: "notable_runs/20200521novisualnocoref/patterns_20200521-113847.pkl"
  htmls_cache: "htmls_cache.pkl"
  htmls_cache_coref: "htmls_cache_coref.pkl"
  coref:
    tuples: "tuples_VG_YOLO_coref.pkl"
  no_coref:
    tuples: "tuples_VG_YOLO.pkl"
  dev: "data_numeric/simone_test_pairs.csv"


parameters:
  similarity: 0.7
  confidence: 0.7
  #######################
  # Sentence processing #
  #######################

  # maximum number of tokens between the two entities
  max_tokens_away: 10

  # minimum number of tokens between the two entities
  min_tokens_away: 1

  # number of tokens to the left and right
  context_window_size: 4

  # the types of tags used to identify the named-entity
  # simple: <PER>Mark Zuckerberg</PER>
  # linked: <PER url=http://en.wikipedia.org/wiki/Mark_Zuckerberg>Mark Elliot Zuckerberg</PER>
  tags_type: "simple"



  ##########################################
  # Bootstrapping Configuration/Parameters #
  ##########################################

  # If parameter Wupdt < 0.5 then the system in effect trusts new examples less on
  # each iteration, which will lead to more conservative patterns and have a
  # damping effect.
  wUpdt: 0.5

  # number of iterations of the system
  number_iterations: 8

  # Weight given to unknown relationships extracted seeds. i.e., since they are
  # not in the seed set, nothing can be said about them
  wUnk: 0.0

  # Weight given to negative seeds, i.e., negative examples of the
  # relationships to be extracted
  wNeg: 1

  # minimum number of patterns that generated a tuple so that tuple can be used
  # in the clustering phase
  min_pattern_support: 2

  # parameters for the cosine similarity between the three
  # relationships vector contexts
  alpha: 0.2
  beta: .5
  gamma: 0.3

  relative_difference_cutoff: .5

  ###################
  # Word2Vec models #
  ###################

  word2vec_path: afp_apw_xin_embeddings.bin

  coreference: True

  visual_confidence: True

  visual_cutoff: .5

  dev_threshold: .3

  visual_at_inference: True


