path:
  test_pairs: "test_pairs.txt"
  unseen_objects: "data_numeric/unseen_objects.txt"
  configuration: "parameters.cfg"
  seeds_file: "data_numeric/seeds_positive.txt"
  negative_seeds: "data_numeric/seeds_negative.txt"
  objects: "data_numeric/VG_YOLO_intersection_train.txt"
  vg_objects: "D:/GitHubD/visual-size-comparison/data/objects.json"
  vg_objects_anchors: "D:/GitHubD/visual-size-comparison/data/test_objects.csv"
  final_seeds_cache: "notable_runs/20200515visualandcoref/final_seeds_20200514-114752.json"
  coref:
    htmls: "htmls_VG_YOLO_coref.pkl"
    tuples: "tuples_VG_YOLO_coref.pkl"
  no_coref:
    htmls: "htmls_VG_YOLO.pkl"
    tuples: "tuples_VG_YOLO.pkl"


parameters:
  similarity: 0.7
  confidence: 0.7


